;; el-getがなければinstall
(add-to-list 'load-path (locate-user-emacs-file "el-get/el-get"))
(unless (require 'el-get nil 'noerror)
  (with-current-buffer
      (url-retrieve-synchronously
       "https://raw.githubusercontent.com/dimitri/el-get/master/el-get-install.el")
    (goto-char (point-max))
    (eval-print-last-sexp)))

;; packages
(el-get-bundle adaptive-wrap)
(el-get-bundle auctex)
(el-get-bundle auctex-latexmk)
(el-get-bundle auto-complete)
(el-get-bundle auto-complete-auctex)
(el-get-bundle dash)
(el-get-bundle dropdown-list)
(el-get-bundle exec-path-from-shell)
(el-get-bundle haskell-mode)
(el-get-bundle helm)
(el-get-bundle highlight-indentation)
(el-get-bundle magit)
(el-get-bundle toshia/mikutter-mode)
(el-get-bundle multi-term)
(el-get-bundle org)
(el-get-bundle popup)
(el-get-bundle scala-mode2)
(el-get-bundle smart-compile)
(el-get-bundle smartparens)
(el-get-bundle bbatsov/solarized-emacs)
(el-get-bundle tuareg)
(el-get-bundle twittering-mode)
(el-get-bundle undo-tree)
(el-get-bundle yasnippet)
(el-get-bundle zlc)
(el-get-bundle gist:6255793:punch)
(el-get-bundle emacsmirror/evil)

(provide 'init-el-get)
