(source gnu)
(source marmalade)
(source melpa)

(depends-on "adaptive-wrap")
(depends-on "auctex")
(depends-on "auctex-latexmk")
(depends-on "auto-complete")
(depends-on "auto-complete-auctex")
(depends-on "auto-java-complete" :git "https://github.com/emacs-java/auto-java-complete.git")
(depends-on "color-theme")
(depends-on "dash")
(depends-on "dropdown-list")
(depends-on "evernote-mode")
(depends-on "exec-path-from-shell")
(depends-on "haskell-mode")
(depends-on "helm")
(depends-on "highlight-indentation")
(depends-on "magit")
(depends-on "mikutter-mode" :git "https://github.com/toshia/mikutter-mode.git")
(depends-on "multi-term")
(depends-on "org")
(depends-on "pallet")
(depends-on "popup")
(depends-on "scala-mode2")
(depends-on "smart-compile")
(depends-on "smartparens")
(depends-on "solarized-theme")
(depends-on "tuareg")
(depends-on "twittering-mode")
(depends-on "undo-tree")
(depends-on "yasnippet")
(depends-on "zlc")
