(source gnu)
(source marmalade)
(source melpa)

(depends-on "adaptive-wrap")
(depends-on "auctex")
(depends-on "auctex-latexmk")
(depends-on "auto-complete")
(depends-on "auto-complete-auctex")
(depends-on "color-theme")
(depends-on "color-theme-solarized")
(depends-on "dash")
(depends-on "evernote-mode")
(depends-on "exec-path-from-shell")
(depends-on "haskell-mode")
(depends-on "highlight-indentation")
(depends-on "mikutter-mode")
(depends-on "multi-term")
(depends-on "org")
(depends-on "pallet")
(depends-on "popup")
(depends-on "shell-pop")
(depends-on "smart-compile")
(depends-on "smartparens")
(depends-on "tabbar")
(depends-on "twittering-mode")
(depends-on "undo-tree")
(depends-on "yasnippet")
(depends-on "zlc")

(depends-on "auto-java-complete" :git "https://github.com/emacs-java/auto-java-complete.git")
